spring.application.name=ai_agent_spring_boot

github.owner=Shoooody
github.repo=lab_mcp_ai_agent_springboot

anthropic.api-key=KEY_132
anthropic.model=claude-opus-4-20250514
anthropic.timeout-seconds=60

openai.api-key=demo
openai.model=gpt-4o-mini
openai.timeout-seconds=60

mcp.base-url=http://localhost:3333
mcp.path=/mcp